package com.frauddetection.model;

public enum AuditEventType {
    TRANSACTION_RECEIVED,
    RULE_TRIGGERED,
    RISK_SCORE_CALCULATED,
    TRANSACTION_FLAGGED,
    TRANSACTION_BLOCKED,
    TRANSACTION_APPROVED,
    MANUAL_REVIEW_REQUESTED,
    MANUAL_REVIEW_COMPLETED,
    FALSE_POSITIVE_RECORDED,
    FRAUD_CONFIRMED
}